version: "3.8"

services:
    postgres:
        image: postgres
        ports:
            - 5432:5432
        shm_size: '1GB'
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./host/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - postgres-network
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - 15432:80
        environment:
            PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
            PGADMIN_DEFAULT_PASSWORD: "pgadmin"
        volumes:
            - ./host/servers.json:/pgadmin4/servers.json
        networks:
            - postgres-network
        depends_on:
            - postgres

networks:
    postgres-network:
        driver: bridge
